[package]
name = "carbonbot"
version = "1.1.1"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-crawler = "1.3.6"
dashmap = "4"
serde_json = "1.0"
log = "0.4"
env_logger = "0.8"
