[package]
name = "carbonbot"
version = "0.1.1"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-crawler = "1.0.9"
dashmap = "4"
rotating-file = "0.3.5"
serde_json = "1.0"
strum = "0.20"
strum_macros = "0.20"
log = "0.4"
env_logger = "0.8"
