[package]
name = "carbonbot"
version = "1.3.2"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-crawler = "1.6.2"
crypto-msg-parser = "1.2.3"
crypto-ws-client = "2.4.8"
dashmap = "4"
redis = "0.20"
serde_json = "1.0"
log = "0.4"
env_logger = "0.8"
