[package]
name = "carbonbot"
version = "1.3.7"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-crawler = "1.6.8"
crypto-msg-parser = "1.2.4"
crypto-ws-client = "2.5.13"
dashmap = "4"
redis = "0.20"
serde_json = "1.0"
log = "0.4"
env_logger = "0.8"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.3.2"
