[package]
name = "crypto-markets"
version = "0.4.6"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"
description   = "Get all trading pairs of a cryptocurrency exchange"
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-markets"
keywords = ["cryptocurrency", "blockchain", "trading"]

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "gzip", "socks"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.20"
strum_macros = "0.20"
