[package]
name = "crypto-crawler"
version = "0.9.4"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"
description   = "Crawl websocket messages from crypto exchanges."
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-crawler"
homepage = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-crawler"

[dependencies]
crypto-ws-client = "1.3.5"
crypto-rest-client = "0.2.6"
log = "0.4.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.20"
strum_macros = "0.20"
