[package]
name = "crypto-crawler"
version = "0.9.8"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"
description   = "Crawl websocket messages from crypto exchanges."
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-crawler"
homepage = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-crawler"

[dependencies]
crypto-markets = "0.3.8"
crypto-rest-client = "0.3.3"
crypto-ws-client = "1.7.1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = "0.20"
strum_macros = "0.20"

[dev_dependencies]
test-case = "1"
