[package]
name = "crypto-rest-client"
version = "0.3.3"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"
description   = "An restful client for all cryptocurrency exchanges."
license = "Apache-2.0"
repository = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-rest-client"
homepage = "https://github.com/soulmachine/crypto-crawler-rs/tree/main/crypto-rest-client"

[dependencies]
lazy_static = "1"
regex = "1"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde_json = "1"
strum = "0.20"
strum_macros = "0.20"
